//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activities.CustomLib.Weather.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activities.CustomLib.Weather.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomLib.
        /// </summary>
        internal static string Group_Name {
            get {
                return ResourceManager.GetString("Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API ключ к OpenWeatherMap.
        /// </summary>
        internal static string WD_ApiKey_Description {
            get {
                return ResourceManager.GetString("WD_ApiKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string WD_ApiKey_ScreenName {
            get {
                return ResourceManager.GetString("WD_ApiKey_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город поиска.
        /// </summary>
        internal static string WD_City_Description {
            get {
                return ResourceManager.GetString("WD_City_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        internal static string WD_City_ScreenName {
            get {
                return ResourceManager.GetString("WD_City_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активность позволяет получить текущий уровень давления в указанном городе..
        /// </summary>
        internal static string WD_CityPressure_Description {
            get {
                return ResourceManager.GetString("WD_CityPressure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнать уровень давления [Pressure] в городе [City]..
        /// </summary>
        internal static string WD_CityPressure_Representation {
            get {
                return ResourceManager.GetString("WD_CityPressure_Representation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давление в городе.
        /// </summary>
        internal static string WD_CityPressure_ScreenName {
            get {
                return ResourceManager.GetString("WD_CityPressure_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активность позволяет получить текущую температуру в указанном городе..
        /// </summary>
        internal static string WD_CityTemperature_Description {
            get {
                return ResourceManager.GetString("WD_CityTemperature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнать температуру [Temperature] в городе [City]..
        /// </summary>
        internal static string WD_CityTemperature_Representation {
            get {
                return ResourceManager.GetString("WD_CityTemperature_Representation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура в городе.
        /// </summary>
        internal static string WD_CityTemperature_ScreenName {
            get {
                return ResourceManager.GetString("WD_CityTemperature_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активность позволяет получить полную информацию о погоде в указанном городе..
        /// </summary>
        internal static string WD_FullWeatherData_Description {
            get {
                return ResourceManager.GetString("WD_FullWeatherData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнать погоду [Weather] в городе [City]..
        /// </summary>
        internal static string WD_FullWeatherData_Representation {
            get {
                return ResourceManager.GetString("WD_FullWeatherData_Representation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погода в городе.
        /// </summary>
        internal static string WD_FullWeatherData_ScreenName {
            get {
                return ResourceManager.GetString("WD_FullWeatherData_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давление в городе по данным OpenWeatherMap.
        /// </summary>
        internal static string WD_Pressure_Description {
            get {
                return ResourceManager.GetString("WD_Pressure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давление.
        /// </summary>
        internal static string WD_Pressure_ScreenName {
            get {
                return ResourceManager.GetString("WD_Pressure_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура в городе по данным OpenWeatherMap.
        /// </summary>
        internal static string WD_Temperature_Description {
            get {
                return ResourceManager.GetString("WD_Temperature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура.
        /// </summary>
        internal static string WD_Temperature_ScreenName {
            get {
                return ResourceManager.GetString("WD_Temperature_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погода в городе по данным OpenWeatherMap в JSON формате..
        /// </summary>
        internal static string WD_Weather_Description {
            get {
                return ResourceManager.GetString("WD_Weather_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погода в городе.
        /// </summary>
        internal static string WD_Weather_ScreenName {
            get {
                return ResourceManager.GetString("WD_Weather_ScreenName", resourceCulture);
            }
        }
    }
}
