//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activities.CustomLib.KPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activities.CustomLib.KPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomLib.
        /// </summary>
        internal static string Group_Name {
            get {
                return ResourceManager.GetString("Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект хранения информации о KPI элемента..
        /// </summary>
        internal static string PIK_ItemKpi_Description {
            get {
                return ResourceManager.GetString("PIK_ItemKpi_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessingItemKpi.
        /// </summary>
        internal static string PIK_ItemKpi_ScreenName {
            get {
                return ResourceManager.GetString("PIK_ItemKpi_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активность, которая позволяет включить таймер обработки элемента..
        /// </summary>
        internal static string PIK_Start_Description {
            get {
                return ResourceManager.GetString("PIK_Start_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уникальный идентификатор элемента..
        /// </summary>
        internal static string PIK_Start_ItemId_Description {
            get {
                return ResourceManager.GetString("PIK_Start_ItemId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string PIK_Start_ItemId_ScreenName {
            get {
                return ResourceManager.GetString("PIK_Start_ItemId_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск таймера объекта [ItemKpi] с указанием уникального идентификатора [ItemId]..
        /// </summary>
        internal static string PIK_Start_Representation {
            get {
                return ResourceManager.GetString("PIK_Start_Representation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить таймер.
        /// </summary>
        internal static string PIK_Start_ScreenName {
            get {
                return ResourceManager.GetString("PIK_Start_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активность, которая позволяет завершить обработку элемента..
        /// </summary>
        internal static string PIK_Stop_Description {
            get {
                return ResourceManager.GetString("PIK_Stop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение об ошибке в случае неудачной обработки элемента..
        /// </summary>
        internal static string PIK_Stop_ErrorMessage_Description {
            get {
                return ResourceManager.GetString("PIK_Stop_ErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение об ошибке.
        /// </summary>
        internal static string PIK_Stop_ErrorMessage_ScreenName {
            get {
                return ResourceManager.GetString("PIK_Stop_ErrorMessage_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановка таймера объекта [ItemKpi] с указанием ошибки обработки элемента [ErrorMessage]..
        /// </summary>
        internal static string PIK_Stop_Representation {
            get {
                return ResourceManager.GetString("PIK_Stop_Representation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выключить таймер.
        /// </summary>
        internal static string PIK_Stop_ScreenName {
            get {
                return ResourceManager.GetString("PIK_Stop_ScreenName", resourceCulture);
            }
        }
    }
}
