//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activities.CustomLib.Files.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activities.CustomLib.Files.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число дней, по окончанию  которых необходимо удалить файл..
        /// </summary>
        internal static string DOF_Days_Description {
            get {
                return ResourceManager.GetString("DOF_Days_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок хранения файлов в днях.
        /// </summary>
        internal static string DOF_Days_ScreenName {
            get {
                return ResourceManager.GetString("DOF_Days_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активность позволяет удалить старые файлы за указанный период времени (например, старые лог-файлы робота)..
        /// </summary>
        internal static string DOF_Description {
            get {
                return ResourceManager.GetString("DOF_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширение файлов, которые требуется удалить. Пример: txt.
        /// </summary>
        internal static string DOF_Extension_Description {
            get {
                return ResourceManager.GetString("DOF_Extension_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширение файла.
        /// </summary>
        internal static string DOF_Extension_ScreenName {
            get {
                return ResourceManager.GetString("DOF_Extension_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь до папки, файлы которой требуется проверить..
        /// </summary>
        internal static string DOF_Folder_Description {
            get {
                return ResourceManager.GetString("DOF_Folder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь до папки.
        /// </summary>
        internal static string DOF_Folder_ScreenName {
            get {
                return ResourceManager.GetString("DOF_Folder_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление файлов папки [Folder], срок хранения которых превысил [Days] дней. Формат поиска: [Extension]..
        /// </summary>
        internal static string DOF_Representation {
            get {
                return ResourceManager.GetString("DOF_Representation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление старых файлов.
        /// </summary>
        internal static string DOF_ScreenName {
            get {
                return ResourceManager.GetString("DOF_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomLib.
        /// </summary>
        internal static string Group_Name {
            get {
                return ResourceManager.GetString("Group_Name", resourceCulture);
            }
        }
    }
}
