//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activities.CustomLib.Text.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activities.CustomLib.Text.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистр написания входящего текста..
        /// </summary>
        internal static string CTR_ChosenRegistry_Description {
            get {
                return ResourceManager.GetString("CTR_ChosenRegistry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистр.
        /// </summary>
        internal static string CTR_ChosenRegistry_ScreenName {
            get {
                return ResourceManager.GetString("CTR_ChosenRegistry_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активность позволяет изменить регистр текста на выбранный (нижний, верхний или комбинированный)..
        /// </summary>
        internal static string CTR_Description {
            get {
                return ResourceManager.GetString("CTR_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Входящий текст, регистр которого требуется изменить..
        /// </summary>
        internal static string CTR_InputText_Description {
            get {
                return ResourceManager.GetString("CTR_InputText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Входящий текст.
        /// </summary>
        internal static string CTR_InputText_ScreenName {
            get {
                return ResourceManager.GetString("CTR_InputText_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат изменения регистра входящего текста..
        /// </summary>
        internal static string CTR_OutputText_Description {
            get {
                return ResourceManager.GetString("CTR_OutputText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат.
        /// </summary>
        internal static string CTR_OutputText_ScreenName {
            get {
                return ResourceManager.GetString("CTR_OutputText_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение регистра текста [InputText] на [ChosenRegistry] с сохранением результата в [OutputText]..
        /// </summary>
        internal static string CTR_Representation {
            get {
                return ResourceManager.GetString("CTR_Representation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение регистра текста.
        /// </summary>
        internal static string CTR_ScreenName {
            get {
                return ResourceManager.GetString("CTR_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomLib.
        /// </summary>
        internal static string Group_Name {
            get {
                return ResourceManager.GetString("Group_Name", resourceCulture);
            }
        }
    }
}
